version: '3.9'

services:
  app:
    build: .
    container_name: cv-builder-be
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:7.0
    container_name: dev-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cv-builder
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.4
    container_name: dev-redis
    restart: always
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
