version: '3.9'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb-cv-builder
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cv_builder_user
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cv_builder
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cv-builder-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis-cv-builder
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cv-builder-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-cv-builder
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cv-builder-network

networks:
  cv-builder-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data:
