export enum Env {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  MONGO_CONNECTION_STRING = 'MONGO_CONNECTION_STRING',
  REDIS_CONNECTION_STRING = 'REDIS_CONNECTION_STRING',

  FRONTEND_ORIGIN = 'FRONTEND_ORIGIN',

  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_USERNAME = 'EMAIL_USERNAME',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',

  AWS_ACCESS_KEY = 'AWS_ACCESS_KEY',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
  AWS_REGION = 'AWS_REGION',
  AWS_BUCKET_NAME = 'AWS_BUCKET_NAME',
  CLOUDFRONT_URL = 'CLOUDFRONT_URL',

  DEFAULT_USER_AVATAR = 'DEFAULT_USER_AVATAR',
}
