export enum Env {
  PORT = 'PORT',
  FRONTEND_ORIGIN = 'FRONTEND_ORIGIN',
  USER_SERVICE_HOST = 'USER_SERVICE_HOST',
  USER_SERVICE_PORT = 'USER_SERVICE_PORT',
  CLERK_WEBHOOK_SECRET = 'CLERK_WEBHOOK_SECRET',
}
