export enum Env {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  MONGO_CONNECTION_STRING = 'MONGO_CONNECTION_STRING',
  REDIS_CONNECTION_STRING = 'REDIS_CONNECTION_STRING',

  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_USERNAME = 'EMAIL_USERNAME',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
}
